# Generated by Django 4.2.9 on 2024-02-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInfoWithTaboo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('ingredient', models.TextField(blank=True, null=True)),
                ('taboo_ingredient', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_info_with_taboo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('food', models.TextField(blank=True, null=True)),
                ('store_name', models.TextField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('tel', models.TextField(blank=True, null=True)),
                ('x좌표', models.FloatField(blank=True, null=True)),
                ('y좌표', models.FloatField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'restaurant_info',
                'managed': False,
            },
        ),
    ]
